import DashboardLayout from "@/components/DashboardLayout";
import { ArticleCard, CalculatorPanel, ContactForm, FreePlanForm, Marquee, PageHero, SectionHeading, SiteFooter, SiteHeader, WaitlistForm } from "@/components/SiteComponents";
import { parseArticleBody, programCatalog, type PublicArticle } from "@/lib/content";
import { useCart } from "@/contexts/CartContext";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";
import { ArrowLeft, ArrowRight, Check, Download, LockKeyhole, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";

function usePlanJump() { const [location, setLocation] = useLocation(); return () => { if (location !== "/") { setLocation("/"); window.setTimeout(() => document.querySelector("#free-plan")?.scrollIntoView({ behavior: "smooth" }), 80); } else document.querySelector("#free-plan")?.scrollIntoView({ behavior: "smooth" }); }; }
function PublicLayout({ children }: { children: React.ReactNode }) { return <div className="site-shell"><SiteHeader /><main>{children}</main><SiteFooter /></div>; }

export function ArticlesPage() { const { data, isLoading } = trpc.articles.list.useQuery(); const articles = (data ?? []) as PublicArticle[]; return <PublicLayout><PageHero kicker="THE GUIDE LIBRARY" title="Straight answers. No fluff." copy="No stupid fitness myths. Just the basics explained in a way that helps you do something with them." visual="guides" /><section className="listing-section"><div className="listing-rail"><p className="eyebrow">NINE GOOD STARTS</p><h2>Less noise.<br />More direction.</h2><p>Read one guide. Apply one thing. Come back for the next question when it becomes useful.</p></div><div className="listing-grid">{isLoading ? <div className="loading-card">Loading guides…</div> : articles.map((article, index) => <ArticleCard article={article} featured={index === 0} key={article.slug} />)}</div></section><section className="bottom-cta"><p className="eyebrow">DON’T JUST READ</p><h2>Put a plan under the idea.</h2><button className="black-button" type="button" onClick={usePlanJump()}>Get the free 7-day starter <ArrowRight size={16} /></button></section></PublicLayout>; }

export function ArticleDetailPage() { const [, params] = useRoute("/articles/:slug"); const slug = params?.slug ?? ""; const { data: article, isLoading } = trpc.articles.bySlug.useQuery({ slug }); const openPlan = usePlanJump(); useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: "instant" as ScrollBehavior }); }, [slug]); if (isLoading) return <PublicLayout><div className="article-loading">Loading the guide…</div></PublicLayout>; if (!article) return <PublicLayout><div className="article-loading"><h1>That guide moved.</h1><Link href="/articles" className="outline-button">Back to articles <ArrowLeft size={16} /></Link></div></PublicLayout>; const body = parseArticleBody(article.body); return <PublicLayout><article className="article-page"><header><Link href="/articles" className="back-link"><ArrowLeft size={16} /> All guides</Link><p className="eyebrow">{article.category}</p><h1>{article.title}</h1><p className="article-lede">{article.excerpt}</p><div className="article-meta"><span>Build With Coach</span><span>·</span><span>5 min read</span></div></header><div className="article-content">{body.intro.map((paragraph) => <p className="intro-paragraph" key={paragraph}>{paragraph}</p>)}{body.sections.map((section, index) => <section key={section.title}><span className="article-number">0{index + 1}</span><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets ? <ul>{section.bullets.map((item) => <li key={item}><Check size={16} />{item}</li>)}</ul> : null}{section.visual ? <figure className="article-inline-visual"><img src={section.visual.src} alt={section.visual.alt} loading="lazy" decoding="async" /></figure> : null}{index === 1 ? <div className="inline-cta"><span><Sparkles size={21} /></span><div><strong>Need a simple start?</strong><p>Claim the free 7-Day Fat Loss Starter and stop building your plan from random clips.</p></div><button className="outline-button" type="button" onClick={openPlan}>Get it <ArrowRight size={15} /></button></div> : null}</section>)}<div className="article-end-cta"><p className="eyebrow">YOUR NEXT REP</p><h2>{body.cta}</h2><button className="black-button" type="button" onClick={openPlan}>Get the free plan <ArrowRight size={16} /></button></div></div></article></PublicLayout>; }

export function ToolsPage() { const openPlan = usePlanJump(); return <PublicLayout><PageHero kicker="FREE TOOLS" title="Use the numbers. Then use your head." copy="Tools do not replace consistency. They do give you a cleaner place to start than copying somebody else’s diet." visual="tools" /><section className="tools-page-section"><CalculatorPanel /><aside className="tools-aside"><p className="eyebrow">A SIMPLE RULE</p><h3>Targets are a starting point, not a life sentence.</h3><p>Run the numbers. Follow the plan for a few weeks. Watch your progress. Make a small adjustment if needed. Your body is not a spreadsheet with feelings.</p><button className="black-button" type="button" onClick={openPlan}>Pair it with the starter <ArrowRight size={16} /></button></aside></section></PublicLayout>; }

export function FreePlanPage() { return <PublicLayout><section className="free-plan-page"><div><p className="eyebrow">FREE 7-DAY FAT LOSS STARTER</p><h1>Your next seven days, <em>sorted.</em></h1><p>A simple seven-day starting plan for men who want to lose fat without confusion, shame, or a thousand rules.</p><div className="big-checks"><span><Check size={17} />Daily workout suggestions</span><span><Check size={17} />Simple food guidance</span><span><Check size={17} />Protein target</span><span><Check size={17} />Basic calorie direction</span></div></div><div className="free-plan-card"><span className="page-seven">7</span><p>GET THE PLAN</p><FreePlanForm /></div></section><Marquee text="NO EXTREME DIETS" /></PublicLayout>; }

export function ProgramsPage() { const { add } = useCart(); const addPlan = (plan: (typeof programCatalog)[number]) => { add({ title: plan.title, price: plan.price, note: plan.note }); window.dispatchEvent(new CustomEvent<string>("bwc-cart-added", { detail: plan.title })); }; return <PublicLayout><PageHero kicker="PROGRAMS" title="Pick the setup you will actually repeat." copy="Four simple PDF plans. Choose the one that matches your equipment, food, and next goal." visual="programs" /><section className="product-list">{programCatalog.map((plan, index) => <article key={plan.title} className={`product-line product-${index + 1}`}><span>0{index + 1}</span><div><p className="eyebrow">{plan.tag}</p><h2>{plan.title}</h2><p>{plan.subtitle}</p></div><strong>{plan.price}</strong><button className="outline-button" type="button" onClick={() => addPlan(plan)}>Add to cart <ArrowRight size={15} /></button></article>)}</section></PublicLayout>; }

export function CartPage() { const { items, remove, clear } = useCart(); const request = () => { if (!items.length) return; window.dispatchEvent(new CustomEvent<string[]>("bwc-open-email-popup", { detail: items.map((item) => item.title) })); clear(); }; return <PublicLayout><section className="cart-page"><div className="cart-page-head"><p className="eyebrow">YOUR PDF CART</p><h1>Plans you picked.<br /><em>Keep the momentum.</em></h1><p>Review your plans, then request delivery with one email. No confusing checkout steps.</p></div>{items.length ? <div className="cart-page-grid"><div className="cart-page-lines">{items.map((item, index) => <article key={item.title}><span>0{index + 1}</span><div><h2>{item.title}</h2><p>{item.note}</p></div><strong>{item.price}</strong><button type="button" onClick={() => remove(item.title)}>Remove</button></article>)}</div><aside className="cart-page-summary"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Send me these PDFs.</h2><p>Choose this and the email form will open with your selected plans ready for delivery.</p><button className="black-button full" type="button" onClick={request}>Buy & request PDFs <ArrowRight size={16} /></button><Link href="/programs" className="text-link">Add another plan <ArrowRight size={15} /></Link></aside></div> : <div className="cart-page-empty"><Download size={30} /><h2>Your cart is empty.</h2><p>Pick one plan that matches your next move. You can review it here whenever you want.</p><Link href="/programs" className="black-button">Explore plans <ArrowRight size={16} /></Link></div>}</section></PublicLayout>; }

export function AboutPage() { return <PublicLayout><PageHero kicker="WHY BUILD WITH COACH EXISTS" title="This is not about fake motivation." copy="It is about real action, honest guidance, and giving men a path forward without using shame as a sales tactic." visual="about" /><section className="about-story"><div className="story-column"><p className="eyebrow">THE SHORT VERSION</p><h2>People get shamed for being fat. That shame can stay for a long time.</h2></div><div><p>It can make people feel stuck, embarrassed, and tired of trying. Build With Coach is for men who want to change without being insulted on the way there.</p><p>The goal is to help men get leaner, stronger, and more confident through simple plans, useful guides, and honest fitness advice. Small actions, repeated for long enough, build the result.</p><Link href="/free-plan" className="black-button">Start with the free plan <ArrowRight size={16} /></Link></div></section></PublicLayout>; }

export function ContactPage() { return <PublicLayout><section className="contact-page"><div><p className="eyebrow">CONTACT</p><h1>Ask a useful question.</h1><p>Have a question, suggestion, or idea? Send a message. This is a growing brand, and useful feedback earns its place.</p><div className="contact-note"><span>01</span><p>For the free plan, use the dedicated form. For anything else, this is the right place.</p></div></div><ContactForm /></section></PublicLayout>; }

export function LoginPage({ signup = false }: { signup?: boolean }) { return <PublicLayout><section className="auth-page"><div className="auth-art"><span className="auth-disc" /><LockKeyhole size={52} /><p>YOUR NEXT<br />CHAPTER</p></div><div className="auth-copy"><p className="eyebrow">{signup ? "CREATE ACCOUNT" : "LOGIN"}</p><h1>{signup ? "Join Build With Coach." : "Welcome back."}</h1><p>{signup ? "Create an account to access future saved plans, downloads, and dashboard features." : "Access your dashboard and future saved plans."}</p><button className="black-button" type="button" onClick={() => startLogin()}>{signup ? "Create account" : "Log in"}<ArrowRight size={16} /></button><p className="auth-switch">{signup ? "Already have access?" : "New here?"} <Link href={signup ? "/login" : "/signup"}>{signup ? "Log in" : "Create an account"}</Link></p></div></section></PublicLayout>; }

export function DashboardPage() { return <DashboardLayout><div className="dashboard-placeholder"><p className="eyebrow">BUILD WITH COACH / DASHBOARD</p><h1>Your system is taking shape.</h1><p>Your future dashboard will be home to the Free 7-Day Starter, saved guides, plan downloads, profile settings, and future paid plans.</p><div className="dashboard-panels"><article><Download size={24} /><h3>Free plan access</h3><p>Your requested resources will appear here.</p></article><article><Sparkles size={24} /><h3>Saved guidance</h3><p>Future saved articles and follow-up checklists.</p></article><article><Check size={24} /><h3>Progress system</h3><p>Future check-ins, habits, and challenges.</p></article></div></div></DashboardLayout>; }
