create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id text not null unique,
  name text,
  email text,
  login_method text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  body text not null,
  category text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.email_subscribers (
  id bigint generated by default as identity primary key,
  name text,
  email text not null,
  consent boolean not null default true,
  source text not null,
  is_pdf_buyer boolean not null default false,
  weekly_challenge_opt_in boolean not null default false,
  time_zone text not null default 'UTC',
  last_weekly_challenge_week text,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists email_subscribers_email_lower_uq on public.email_subscribers (lower(email));

create table if not exists public.free_plan_signups (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  plan_name text not null,
  status text not null default 'requested',
  created_at timestamptz not null default now()
);

create index if not exists free_plan_signups_email_idx on public.free_plan_signups (lower(email));

create table if not exists public.future_products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  price text not null,
  status text not null default 'coming_soon',
  created_at timestamptz not null default now()
);

create table if not exists public.downloads (
  id bigint generated by default as identity primary key,
  email text not null,
  resource_name text not null,
  status text not null default 'pending_delivery',
  created_at timestamptz not null default now()
);

create index if not exists downloads_email_idx on public.downloads (lower(email));

create table if not exists public.pdf_delivery_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  status text not null default 'pending_provider_setup',
  provider_message_id text,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pdf_delivery_requests_email_idx on public.pdf_delivery_requests (lower(email));

create table if not exists public.pdf_delivery_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.pdf_delivery_requests(id) on delete cascade,
  plan_name text not null,
  storage_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists pdf_delivery_items_request_idx on public.pdf_delivery_items (request_id);

create table if not exists public.buyer_access_codes (
  id bigint generated by default as identity primary key,
  email text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  attempts integer not null default 0 check (attempts >= 0),
  created_at timestamptz not null default now()
);

create index if not exists buyer_access_codes_email_idx on public.buyer_access_codes (lower(email));

create table if not exists public.weekly_challenge_schedules (
  id bigint generated by default as identity primary key,
  schedule_cron_task_uid text not null unique,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.weekly_challenge_deliveries (
  id bigint generated by default as identity primary key,
  subscriber_id bigint not null references public.email_subscribers(id) on delete cascade,
  week_key text not null,
  challenge_key text not null,
  status text not null default 'pending',
  provider_message_id text,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (subscriber_id, week_key)
);

create index if not exists weekly_challenge_deliveries_week_idx on public.weekly_challenge_deliveries (week_key);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.story_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  story text not null,
  photo_key text not null,
  photo_url text not null,
  photo_name text not null,
  photo_mime text not null check (photo_mime in ('image/jpeg', 'image/png', 'image/webp')),
  consent boolean not null default false,
  status text not null default 'pending_review',
  created_at timestamptz not null default now()
);

create index if not exists story_submissions_status_idx on public.story_submissions (status);

alter table public.users enable row level security;
alter table public.articles enable row level security;
alter table public.email_subscribers enable row level security;
alter table public.free_plan_signups enable row level security;
alter table public.future_products enable row level security;
alter table public.downloads enable row level security;
alter table public.pdf_delivery_requests enable row level security;
alter table public.pdf_delivery_items enable row level security;
alter table public.buyer_access_codes enable row level security;
alter table public.weekly_challenge_schedules enable row level security;
alter table public.weekly_challenge_deliveries enable row level security;
alter table public.contact_messages enable row level security;
alter table public.story_submissions enable row level security;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at before update on public.users for each row execute function public.set_updated_at();

drop trigger if exists set_articles_updated_at on public.articles;
create trigger set_articles_updated_at before update on public.articles for each row execute function public.set_updated_at();

drop trigger if exists set_pdf_delivery_requests_updated_at on public.pdf_delivery_requests;
create trigger set_pdf_delivery_requests_updated_at before update on public.pdf_delivery_requests for each row execute function public.set_updated_at();

drop trigger if exists set_weekly_challenge_schedules_updated_at on public.weekly_challenge_schedules;
create trigger set_weekly_challenge_schedules_updated_at before update on public.weekly_challenge_schedules for each row execute function public.set_updated_at();

drop trigger if exists set_weekly_challenge_deliveries_updated_at on public.weekly_challenge_deliveries;
create trigger set_weekly_challenge_deliveries_updated_at before update on public.weekly_challenge_deliveries for each row execute function public.set_updated_at();

create or replace function public.create_free_plan_signup(
  p_name text,
  p_email text,
  p_weekly_challenge_opt_in boolean,
  p_time_zone text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare signup_id bigint;
begin
  insert into public.free_plan_signups (name, email, plan_name, status)
  values (p_name, lower(trim(p_email)), '7-Day Fat Loss Starter', 'requested')
  returning id into signup_id;

  insert into public.downloads (email, resource_name, status)
  values (lower(trim(p_email)), '7-Day Fat Loss Starter', 'pending_delivery');

  insert into public.email_subscribers (name, email, consent, source, is_pdf_buyer, weekly_challenge_opt_in, time_zone)
  values (p_name, lower(trim(p_email)), p_weekly_challenge_opt_in, 'free_plan', p_weekly_challenge_opt_in, p_weekly_challenge_opt_in, coalesce(nullif(p_time_zone, ''), 'UTC'))
  on conflict ((lower(email))) do update set
    name = excluded.name,
    consent = excluded.consent,
    source = excluded.source,
    is_pdf_buyer = excluded.is_pdf_buyer,
    weekly_challenge_opt_in = excluded.weekly_challenge_opt_in,
    time_zone = excluded.time_zone,
    unsubscribed_at = case when excluded.weekly_challenge_opt_in then null else now() end;

  return signup_id;
end;
$$;

create or replace function public.create_cart_request(
  p_name text,
  p_email text,
  p_items jsonb,
  p_weekly_challenge_opt_in boolean,
  p_time_zone text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare request_id bigint;
item jsonb;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'At least one plan is required';
  end if;

  insert into public.pdf_delivery_requests (name, email, status)
  values (p_name, lower(trim(p_email)), 'pending_provider_setup')
  returning id into request_id;

  for item in select * from jsonb_array_elements(p_items) loop
    insert into public.pdf_delivery_items (request_id, plan_name, storage_key)
    values (request_id, item ->> 'title', item ->> 'storageKey');
    insert into public.downloads (email, resource_name, status)
    values (lower(trim(p_email)), item ->> 'title', 'pending_delivery');
  end loop;

  insert into public.email_subscribers (name, email, consent, source, is_pdf_buyer, weekly_challenge_opt_in, time_zone)
  values (p_name, lower(trim(p_email)), p_weekly_challenge_opt_in, 'cart_pdf_request', true, p_weekly_challenge_opt_in, coalesce(nullif(p_time_zone, ''), 'UTC'))
  on conflict ((lower(email))) do update set
    name = excluded.name,
    consent = excluded.consent,
    source = excluded.source,
    is_pdf_buyer = true,
    weekly_challenge_opt_in = excluded.weekly_challenge_opt_in,
    time_zone = excluded.time_zone,
    unsubscribed_at = case when excluded.weekly_challenge_opt_in then null else now() end;

  return request_id;
end;
$$;

grant execute on function public.create_free_plan_signup(text, text, boolean, text) to service_role;
grant execute on function public.create_cart_request(text, text, jsonb, boolean, text) to service_role;

create or replace function public.redeem_buyer_access_code(
  p_email text,
  p_code_hash text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare matched_id bigint;
updated_count integer;
begin
  select id into matched_id
  from public.buyer_access_codes
  where lower(email) = lower(trim(p_email))
    and code_hash = p_code_hash
    and used_at is null
    and expires_at >= now()
    and attempts < 5
  order by created_at desc
  limit 1;

  if matched_id is null then
    update public.buyer_access_codes
    set attempts = attempts + 1
    where lower(email) = lower(trim(p_email))
      and used_at is null
      and expires_at >= now()
      and attempts < 5;
    return false;
  end if;

  update public.buyer_access_codes
  set used_at = now()
  where id = matched_id and used_at is null;
  get diagnostics updated_count = row_count;
  return updated_count = 1;
end;
$$;

grant execute on function public.redeem_buyer_access_code(text, text) to service_role;
